In [66]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [67]:
df=pd.read_csv("customer.csv")

In [68]:
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [69]:
df=df.iloc[:,2:]
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

### Ordinal encoding

* if the input column is ordinal then we do ordinal encoding

In [70]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,:2],df.iloc[:,-1],test_size=0.2,random_state=0)

In [71]:
x_train

review education
33     Good        PG
35     Poor    School
26     Poor        PG
34  Average    School
18     Good    School
7      Poor    School
14     Poor        PG
45     Poor        PG
48     Good        UG
29  Average        UG
15     Poor        UG
30  Average        UG
32  Average        UG
16     Poor        UG
42     Good        PG
20  Average    School
43     Poor        PG
8   Average        UG
13  Average    School
25     Good    School
5   Average    School
17     Poor        UG
40     Good    School
49     Good        UG
1      Poor        UG
12     Poor    School
37  Average        PG
24  Average        PG
6      Good    School
23     Good    School
36     Good        UG
21  Average        PG
19     Poor        PG
9      Good        UG
39     Poor        PG
46     Poor        PG
3      Good        PG
0   Average    School
47     Good        PG
44  Average        UG

- so basically here we have to  assign the ordinal column like this we have done in object creating process
- always understand while transforming first do fit() and only train the model on train data

In [72]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[["Poor","Average","Good"],["School","UG","PG"]])
oe.fit(x_train)

x_train_encode=oe.transform(x_train)
x_test_encode=oe.transform(x_test)

- so basically we have done here ordinal encoding 
- so we do ordinal encoding on input columns if the feature is categorical(>>ordinal)
- ordinal ex:- good>avg>bad

### Label encoding

- when the output column is categorical then we use label encoding

In [73]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

le.fit(y_train)

y_train_encode=le.transform(y_train)
y_test_encode=le.transform(y_test)

In [74]:
y_train_encode,y_test_encode

(array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0]),
 array([0, 1, 1, 1, 0, 0, 0, 1, 1, 0]))

### One Hot Encoding

In [75]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [76]:
df=pd.read_csv("cars.csv")
df

brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

# a) one hot endocing using pandas

In [77]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,:4],df.iloc[:,-1],test_size=0.3,random_state=0)

In [78]:
from sklearn.preprocessing import OneHotEncoder
oh=OneHotEncoder(drop="first",dtype=np.int32)

x_train_encode=oh.fit_transform(x_train[["fuel","owner"]]).toarray()
x_test_encode=oh.transform(x_test[["fuel","owner"]]).toarray()

In [79]:
x_train_encode

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], shape=(5689, 7), dtype=int32)

In [80]:
x_test_encode

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], shape=(2439, 7), dtype=int32)

In [81]:
np.hstack((x_train.iloc[:,:2].values,x_train_encode)).shape

(5689, 9)

### b) one hot encoding with top categories

In [82]:
counts=df["brand"].value_counts()
counts.head()

brand
Maruti      2448
Hyundai     1415
Mahindra     772
Tata         734
Toyota       488
Name: count, dtype: int64

In [83]:
df["brand"].nunique()
thresold=100
repl=counts[counts <= thresold].index

In [86]:
pd.get_dummies(df["brand"].replace(repl,"uncomman")).astype(int)

BMW  Chevrolet  Ford  Honda  Hyundai  Mahindra  Maruti  Renault  Skoda  \
0       0          0     0      0        0         0       1        0      0   
1       0          0     0      0        0         0       0        0      1   
2       0          0     0      1        0         0       0        0      0   
3       0          0     0      0        1         0       0        0      0   
4       0          0     0      0        0         0       1        0      0   
...   ...        ...   ...    ...      ...       ...     ...      ...    ...   
8123    0          0     0      0        1         0       0        0      0   
8124    0          0     0      0        1         0       0        0      0   
8125    0          0     0      0        0         0       1        0      0   
8126    0          0     0      0        0         0       0        0      0   
8127    0          0     0      0        0         0       0        0      0   

      Tata  Toyota  Volkswagen  uncomman  
0        0       0           0         0  
1        0       0           0         0  
2        0       0           0         0  
3        0       0           0         0  
4        0       0           0         0  
...    ...     ...         ...       ...  
8123     0       0           0         0  
8124     0       0           0         0  
8125     0       0           0         0  
8126     1       0           0         0  
8127     1       0           0         0  

[8128 rows x 13 columns]