In [336]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.filterwarnings("ignore")
from sklearn.linear_model import LinearRegression

In [337]:
# first we will do with the help of pandas

In [338]:
np.random.seed(42)   
df = pd.read_csv("50_Startups.csv")
df.drop(columns=["State"], inplace=True)
df = np.round(df/10000, 0).sample(5)

In [339]:
df=df.iloc[:,:3]

In [340]:
# first i will do some nan values in the data
df.iloc[1,0]=np.nan
df.iloc[3,1]=np.nan
df.iloc[4,2]=np.nan

In [341]:
# now we will replace all nan values with the mean of that particular column
df["R&D Spend"].fillna(df["R&D Spend"].mean(),inplace=True)
df["Administration"].fillna(df["Administration"].mean(),inplace=True)
df["Marketing Spend"].fillna(df["Marketing Spend"].mean(),inplace=True)

In [342]:
#so here we have replace the nan values with the mean
# 0th iteration
df

R&D Spend  Administration  Marketing Spend
13        9.0           14.00            25.00
39        6.0            8.00            17.00
30        6.0           12.00             9.00
45        0.0           12.25             0.00
17        9.0           15.00            12.75

In [343]:
# now we will make the value of col 1 again nan which was nan
df1=df.copy()

In [344]:
df1.iloc[1,0]=np.nan

In [345]:
df1

R&D Spend  Administration  Marketing Spend
13        9.0           14.00            25.00
39        NaN            8.00            17.00
30        6.0           12.00             9.00
45        0.0           12.25             0.00
17        9.0           15.00            12.75

In [346]:
#now we will train the data and will predict the value
x_train=df.iloc[[0,2,3,4],[1,2]]
y_train=df.iloc[[0,2,3,4],[0]]
x_test=df.iloc[1,1:].values.reshape(1,2)

In [347]:
x_train

Administration  Marketing Spend
13           14.00            25.00
30           12.00             9.00
45           12.25             0.00
17           15.00            12.75

In [348]:
y_train

R&D Spend
13        9.0
30        6.0
45        0.0
17        9.0

In [349]:
x_test

array([[ 8., 17.]])

In [350]:
lr=LinearRegression()
lr.fit(x_train,y_train)
lr.predict(x_test)

array([[1.9356771]])

In [351]:
df1.iloc[1,0]=1.93

In [352]:
df1

R&D Spend  Administration  Marketing Spend
13       9.00           14.00            25.00
39       1.93            8.00            17.00
30       6.00           12.00             9.00
45       0.00           12.25             0.00
17       9.00           15.00            12.75

In [353]:
# Remove the col2 imputed value

In [354]:
df1.iloc[3,1]=np.nan

In [355]:
df1

R&D Spend  Administration  Marketing Spend
13       9.00            14.0            25.00
39       1.93             8.0            17.00
30       6.00            12.0             9.00
45       0.00             NaN             0.00
17       9.00            15.0            12.75

In [356]:
x_train=df1.iloc[[0,1,2,4],[0,2]]
y_train=df1.iloc[[0,1,2,4],1]
x_test=df1.iloc[3,[0,2]].values.reshape(1,2)
lr=LinearRegression()
lr.fit(x_train,y_train)
lr.predict(x_test)

array([7.08609])

In [357]:
df1.iloc[3,1]=7.08

In [358]:
df1.iloc[4,-1] =np.nan
df1

R&D Spend  Administration  Marketing Spend
13       9.00           14.00             25.0
39       1.93            8.00             17.0
30       6.00           12.00              9.0
45       0.00            7.08              0.0
17       9.00           15.00              NaN

In [359]:
# Remove the col3 imputed value
df1.iloc[4,-1] = np.nan
x_train = df1.iloc[0:4,0:2]
y_train = df1.iloc[0:4,-1]
x_test=df1.iloc[4,[0,1]].values.reshape(1,2)
lr=LinearRegression()
lr.fit(x_train,y_train)
lr.predict(x_test)

array([2.69251092])

In [360]:
df1.iloc[4,-1] = 2.69

In [361]:
# After 1st Iteration
df1

R&D Spend  Administration  Marketing Spend
13       9.00           14.00            25.00
39       1.93            8.00            17.00
30       6.00           12.00             9.00
45       0.00            7.08             0.00
17       9.00           15.00             2.69

In [362]:
# Subtract 0th iteration from 1st iteration
df1 - df

R&D Spend  Administration  Marketing Spend
13       0.00            0.00             0.00
39      -4.07            0.00             0.00
30       0.00            0.00             0.00
45       0.00           -5.17             0.00
17       0.00            0.00           -10.06

In [363]:
df2 = df1.copy()
df2.iloc[1,0] = np.nan
df2

R&D Spend  Administration  Marketing Spend
13        9.0           14.00            25.00
39        NaN            8.00            17.00
30        6.0           12.00             9.00
45        0.0            7.08             0.00
17        9.0           15.00             2.69

In [364]:
X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

array([1.89284171])

In [365]:
df2.iloc[1,0] = 1.89

In [366]:
df2.iloc[3,1] = np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

array([7.05117981])

In [367]:
df2.iloc[3,1] = 7.05

In [368]:
df2.iloc[4,-1] = np.nan

X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

array([1.45020162])

In [369]:
df2.iloc[4,-1] = 1.45

In [370]:
df2

R&D Spend  Administration  Marketing Spend
13       9.00           14.00            25.00
39       1.89            8.00            17.00
30       6.00           12.00             9.00
45       0.00            7.05             0.00
17       9.00           15.00             1.45

In [371]:
df2 - df1

R&D Spend  Administration  Marketing Spend
13       0.00            0.00             0.00
39      -0.04            0.00             0.00
30       0.00            0.00             0.00
45       0.00           -0.03             0.00
17       0.00            0.00            -1.24

In [372]:
df3 = df2.copy()
df3.iloc[1,0] = np.nan
df3

R&D Spend  Administration  Marketing Spend
13        9.0           14.00            25.00
39        NaN            8.00            17.00
30        6.0           12.00             9.00
45        0.0            7.05             0.00
17        9.0           15.00             1.45

In [373]:
X = df3.iloc[[0,2,3,4],1:3]
y = df3.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

array([1.8807113])

In [374]:
df3.iloc[1,0] = 1.88

In [375]:
df3.iloc[3,1] = np.nan
X = df3.iloc[[0,1,2,4],[0,2]]
y = df3.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

array([7.04325189])

In [376]:
df3.iloc[3,1] = 7.04

In [377]:
df3.iloc[4,-1] = np.nan

X = df3.iloc[0:4,0:2]
y = df3.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[4,0:2].values.reshape(1,2))

array([1.10355867])

In [378]:
df3.iloc[4,-1]=1.10

In [379]:
df3

R&D Spend  Administration  Marketing Spend
13       9.00           14.00             25.0
39       1.88            8.00             17.0
30       6.00           12.00              9.0
45       0.00            7.04              0.0
17       9.00           15.00              1.1

In [380]:
df3 - df2

R&D Spend  Administration  Marketing Spend
13       0.00            0.00             0.00
39      -0.01            0.00             0.00
30       0.00            0.00             0.00
45       0.00           -0.01             0.00
17       0.00            0.00            -0.35

- like this if we do the iterations unti the difference is near to o

In [381]:
# now we will do with the help of sklearn

In [382]:
df=pd.read_csv("train.csv",usecols=["Survived","Age","Fare"])
df.head()

Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [383]:
df.isnull().mean()*100

Survived     0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [384]:
df.isnull().sum()

Survived      0
Age         177
Fare          0
dtype: int64

In [385]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],random_state=0,test_size=0.2)

In [386]:
x_train.head()

Age     Fare
140   NaN  15.2458
439  31.0  10.5000
817  31.0  37.0042
378  20.0   4.0125
491  21.0   7.2500

In [392]:
# first we have to enalble iterative imputer then we have impute it we can also gvive iteration
# max_iter=5, we ccan give this parameter also       
from sklearn.pipeline import Pipeline
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.tree import DecisionTreeClassifier
pipe=Pipeline([
    ("impute",IterativeImputer(random_state=42)),
    ("model",DecisionTreeClassifier())
])

In [393]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('impute', IterativeImputer(random_state=42)),
                ('model', DecisionTreeClassifier())])

In [394]:
y_pred=pipe.predict(x_test)

In [395]:
from sklearn.metrics import accuracy_score
print("accuracy",accuracy_score(y_test,y_pred))

accuracy 0.6759776536312849
