In [229]:
class meralr:
    def __init__(self):
        self.m=None
        self.b=None

    def fit(self,x_train,y_train):
        num= 0
        den= 0
        for i in range(x_train.shape[0]):
            num = num + ((x_train[i] - x_train.mean()) * (y_train[i] - y_train.mean()))
            den= den + ((x_train[i] - x_train.mean()) * (x_train[i] - x_train.mean()))
            self.m= num / den
            self.b= y_train.mean()- (self.m *x_train.mean())
        
    def predict(self,x_test):
        return (self.m * x_test) + self.b

In [230]:
import pandas as pd
import numpy as np

In [231]:
df=pd.read_csv("placement_.csv")
df.head()

,cgpa,package
0,6.89,3.26
1,5.12,1.98
2,7.82,3.25
3,7.42,3.67
4,6.94,3.57


In [232]:
x=df.iloc[:,0]
y=df.iloc[:,1]

In [233]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [234]:
x_train=x_train.values.reshape(-1,1)
x_test=x_test.values.reshape(-1,1)
y_train=y_train.values.reshape(-1,1)

In [235]:
y_train

array([[2.83],
       [1.63],
       [3.42],
       [2.37],
       [3.52],
       [4.25],
       [2.31],
       [3.28],
       [2.88],
       [1.54],
       [3.34],
       [2.31],
       [3.14],
       [2.84],
       [3.67],
       [2.71],
       [3.26],
       [2.93],
       [4.02],
       [2.74],
       [2.01],
       [2.61],
       [3.89],
       [2.83],
       [3.99],
       [4.  ],
       [3.09],
       [3.91],
       [3.79],
       [2.77],
       [2.4 ],
       [2.66],
       [3.13],
       [3.52],
       [2.42],
       [2.72],
       [4.06],
       [3.42],
       [2.16],
       [3.18],
       [2.44],
       [2.26],
       [3.89],
       [2.46],
       [3.54],
       [2.09],
       [3.25],
       [3.31],
       [2.1 ],
       [3.24],
       [2.76],
       [1.86],
       [3.67],
       [4.03],
       [2.57],
       [3.63],
       [3.5 ],
       [2.6 ],
       [3.08],
       [4.1 ],
       [3.04],
       [3.48],
       [4.43],
       [3.26],
       [2.42],
       [3.76],
       [2.

In [236]:
lr=meralr()

In [237]:
lr.fit(x_train,y_train)

In [241]:
lr.predict(x_test[0])

array([2.97012606])

In [239]:
x_test[0]

array([6.94])

In [ ]:
# this is a function which is made by me